config/routes.rb
Rails.application.routes.draw do
  get 'ratings/create'
  get '/movies/new', to: 'movies#new'
  get 'reports/filtr_by_category'
  get '/movies/:id', to: 'movies#show'
  
  # , as: 'movie'
  resources :movies
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "movies#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :category
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie
  validates :rating, numericality: {only_integer: true, in: 1..10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
     @movies = Movie.joins(:category)
        .select(:id, :movie_title, :text, :rating, :category_name)
        .paginate(page: params[:page], per_page: 4)
     @categories = Category.all   
    
    # also work
    # @movies = Movie.joins(:category).select('movies.movie_title, movies.text, movies.rating, categories.category_name')
  end

  # GET /movies/1 or /movies/1.json
  def show
    @movie = Movie.joins(:category).select(:id, :movie_title, :text, :rating, :category_name).find(params[:id])
 
    @average_rating = Rating.where(movie_id: params[:id]).average(:rating)
    @average_rating == nil ? @average_rating = "No one voted for rating" : @average_rating.round(2)
    
   
  end

  # GET /movies/new
  def new
     @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:id, :movie_title, :text, :rating, :category_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def new
    @rating = Rating.new
  end


  def create
    @rating = Rating.create(rating_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def rating_params
    params.require(:user_rating).permit(:rating, :movie_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def filtr_by_category
    @movies = Movie.joins(:category)
    .select(:id, :movie_title, :text, :rating, :category_name)
    .where(category_id: params[:category][:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category name:</strong>
    <%= category.category_name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category_name, style: "display: block" %>
    <%= form.text_field :category_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMDBCloneB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :movie_title, style: "display: block" %>
    <%= form.text_field :movie_title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Movie title:</strong>
    <%= movie.movie_title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= movie.text %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= movie.rating %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= movie.category_id %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <%= link_to "New movie", new_movie_path %>

<!--Block for Filter by category-->
  <form action="">
    <label>Choose a category:</label>
      <select name="category[id]">
        <% @categories.each do |category| %>
          <option value="<%=category.id%>"> <%=category.category_name%></option>
        <%end%>
      </select>
    <button type="submit" class="btn btn-success" formaction="/reports/filtr_by_category">Filter by category</button>
  </form>
<!--end block for Filter by category-->

<!--Block for iterate each movie on page-->
  <ol>
    <% @movies.each do |movie| %>
      <li>
        <strong>Title:</strong> <%= movie.movie_title%>,<br>
        <strong>Text:</strong> <%= movie.text%>,<br>
        <strong>Category:</strong> <%= movie.category_name%>,<br>
        <!--Block for choosing ratig and sent do DB-->
        <form>
         <input type="hidden" name="user_rating[movie_id]" value="<%=movie.id%>">
         <label>Choose a rating:</label>
          <select name="user_rating[rating]">
            <% for value_rating in 1..10 do %>
            <option value="<%=value_rating%>"> <%=value_rating%></option>
            <%end%>
          </select>
          <button type="submit" class="btn btn-info" formaction="ratings/create">Send a rating</button>
        </form>
        <!--end block for choosing ratig and sent do DB-->
        <%= link_to "Show this movie", movie_path(movie.id)%>
        <hr>
      </li>
    <% end %>
  </ol>
  <!--end block for iterate each movie on page-->


  <!--Pagination-->

  <%= will_paginate @movies%>

<%# renderer: BootstrapPagination::Rails %>

<!--Bootstrap online-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>
 
<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>


<div id="movies">
  <ol>
    <strong>Title:</strong> <%= @movie.movie_title%>,<br>
    <strong>Text:</strong> <%= @movie.text%>,<br>
    <strong>Category:</strong> <%= @movie.category_name%>,<br>
    <strong>Average rating:</strong> <%=@average_rating%><br>
  </ol>
<!--Bootstrap online-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</div>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/reports/filtr_by_category.html.erb
<h1>Reports#filtr_by_category</h1>
<p>Find me in app/views/reports/filtr_by_category.html.erb</p>


<div>
<ol>
  <% @movies.each do |movie| %>
  <li>
    <strong>Title:</strong> <%= movie.movie_title%>,<br>
     <strong>Text:</strong> <%= movie.text%>,<br>
     <strong>Category:</strong> <%= movie.category_name%>,<br>
         
     <%= link_to "Show this movie", movie_path(movie.id)%>
     <hr>
     </li>
  <% end %>
  </ol>

  <%= link_to "Back to movies", movies_path %>
</div>